from collections import defaultdict
from collections.abc import Callable, Sequence

import numpy as np
from pgmpy.factors.discrete import DiscreteFactor
from pgmpy.inference import BeliefPropagationWithMessagePassing
from pgmpy.models import FactorGraph

from crg_ce.graph.data_types import ConfidenceGraph
from crg_ce.graph.nodes import GSNGoalNode
from crg_ce.graph.utils import outdated_aggregated_rationale

EMISSION_BIN_UPPER_BOUNDS = np.array([0.2, 0.4, 0.7, 0.9])

# Rows are score bins; columns are [Z=False, Z=True].
EMISSION_PROBABILITIES = np.array(
    [
        [0.30, 0.12],  # S in [0.0, 0.2)
        [0.10, 0.05],  # S in [0.2, 0.4)
        [0.15, 0.10],  # S in [0.4, 0.7)
        [0.13, 0.08],  # S in [0.7, 0.9)
        [0.32, 0.65],  # S in [0.9, 1.0]
    ]
)


def make_decomposition_factor(parent_id: str, child_ids: Sequence[str]) -> DiscreteFactor:
    """Return P(children | parent) for a necessary-and-sufficient conjunction."""
    if not child_ids:
        raise ValueError(f"Decomposition parent {parent_id!r} has no children")

    values = np.zeros((2,) * (len(child_ids) + 1))
    values[0] = 1 / (2 ** len(child_ids) - 1)
    values[(0, *(1 for _ in child_ids))] = 0
    values[(1, *(1 for _ in child_ids))] = 1
    return DiscreteFactor(
        variables=[parent_id, *child_ids],
        cardinality=[2] * (len(child_ids) + 1),
        values=values,
    )


def make_particularization_factor(parent_id: str, child_id: str) -> DiscreteFactor:
    """Return the deterministic equality factor for a particularization."""
    return DiscreteFactor(
        variables=[parent_id, child_id],
        cardinality=[2, 2],
        values=np.array([[1.0, 0.0], [0.0, 1.0]]),
    )


def make_leaf_confidence_factor_v1(goal: GSNGoalNode) -> DiscreteFactor:
    """Represent a leaf confidence as virtual evidence with weights [1-c, c]."""
    if goal.confidence < 0:
        raise ValueError(f"Leaf goal {goal.id!r} has no confidence observation")
    return DiscreteFactor(
        variables=[goal.id],
        cardinality=[2],
        values=[1 - goal.confidence, goal.confidence],
    )


def make_leaf_confidence_factor_v2(goal: GSNGoalNode) -> DiscreteFactor:
    """Represent the observed score using the paper's emission distribution."""
    score = goal.confidence
    if not 0.0 <= score <= 1.0:
        raise ValueError(f"Leaf goal {goal.id!r} has invalid confidence {score}")

    # Exact boundaries begin the next bin: 0.2 -> 1, 0.4 -> 2, 0.7 -> 3, and 0.9 -> 4.
    bin_index = np.searchsorted(EMISSION_BIN_UPPER_BOUNDS, score, side="right")
    emission = EMISSION_PROBABILITIES[bin_index]
    return DiscreteFactor(
        variables=[goal.id],
        cardinality=[2],
        values=emission,
    )


def _confidence_graph_to_simple_bp_factor_graph(
    graph: ConfidenceGraph,
    leaf_confidence_factor_factory: Callable[[GSNGoalNode], DiscreteFactor],
) -> FactorGraph:
    """Build a goal-only factor graph using the selected leaf-score observation model."""
    # Exclude evidence nodes: this model has one binary variable per goal claim.
    goals_by_id = {node.id: node for node in graph.nodes if isinstance(node, GSNGoalNode)}
    # A goal-free graph cannot define the requested probabilistic model.
    if not goals_by_id:
        raise ValueError("Belief propagation requires at least one goal node")

    # Group child goal variables by their parent goal variable.
    child_ids_by_parent_id: dict[str, list[str]] = defaultdict(list)
    # Track the relationship used by each parent's complete child group.
    relationship_types_by_parent_id: dict[str, set[str | None]] = defaultdict(set)
    # Track parents per child so each non-root goal has one parent.
    parent_ids_by_child_id: dict[str, list[str]] = defaultdict(list)
    # ConfidenceGraph edges point from child to parent.
    for edge in graph.edges:
        # Ignore every edge involving a non-goal node.
        if edge.source not in goals_by_id or edge.target not in goals_by_id:
            continue
        # Record this child in the factor associated with its parent.
        child_ids_by_parent_id[edge.target].append(edge.source)
        # Record whether the factor is a decomposition or particularization.
        relationship_types_by_parent_id[edge.target].add(edge.relationship_type)
        # Record the reverse lookup used to identify roots and invalid sharing.
        parent_ids_by_child_id[edge.source].append(edge.target)

    # Goal nodes generated by our GSN construction cannot be shared between parents.
    shared_child_goal_ids = sorted(
        goal_id for goal_id, parent_ids in parent_ids_by_child_id.items() if len(parent_ids) > 1
    )
    # Reject goal structures which violate that generated-tree invariant.
    if shared_child_goal_ids:
        raise ValueError(f"Goal nodes have multiple parents: {shared_child_goal_ids}")

    # The serialized graph must identify its single root goal.
    if graph.goal_zero_node_id is None or graph.goal_zero_node_id not in goals_by_id:
        raise ValueError("Belief propagation requires goal_zero_node_id to identify a goal node")

    # Roots are goals which are never the child of another goal.
    root_ids = set(goals_by_id) - set(parent_ids_by_child_id)
    # Our generated GSN goal structure has exactly one root: goal zero.
    if root_ids != {graph.goal_zero_node_id}:
        raise ValueError(
            f"Goal graph roots must equal goal_zero_node_id={graph.goal_zero_node_id!r}, got {sorted(root_ids)}"
        )

    # Verify every non-root goal's parent chain terminates at goal zero.
    for goal_id in goals_by_id:
        visited_goal_ids: set[str] = set()
        ancestor_id = goal_id
        while ancestor_id in parent_ids_by_child_id:
            if ancestor_id in visited_goal_ids:
                raise ValueError(f"Cycle in goal graph involving goal {ancestor_id!r}")
            visited_goal_ids.add(ancestor_id)
            ancestor_id = parent_ids_by_child_id[ancestor_id][0]
        if ancestor_id != graph.goal_zero_node_id:
            raise ValueError(f"Goal {goal_id!r} is not connected to goal zero {graph.goal_zero_node_id!r}")

    # Accumulate all structural, prior, and observation factors before wiring the model.
    factors: list[DiscreteFactor] = []
    # Create exactly one structural factor for each non-leaf parent goal.
    for parent_id, child_ids in child_ids_by_parent_id.items():
        # All children of one parent must express the same relationship semantics.
        relationship_types = relationship_types_by_parent_id[parent_id]
        # A decomposition models the parent as the conjunction of its children.
        if relationship_types == {"decomposes_from"}:
            factors.append(make_decomposition_factor(parent_id, child_ids))
        # A particularization models the abstract and concrete claims as equal.
        elif relationship_types == {"particularizes"}:
            # Particularization is defined only for one concrete child.
            if len(child_ids) != 1:
                raise ValueError(f"Particularization parent {parent_id!r} has {len(child_ids)} children")
            factors.append(make_particularization_factor(parent_id, child_ids[0]))
        # Mixed or missing relationship labels have no factor definition in v1.
        else:
            raise ValueError(
                f"Goal parent {parent_id!r} has unsupported or mixed relationship types: "
                f"{sorted(str(value) for value in relationship_types)}"
            )

    # Give goal zero the balanced prior used by the proof of concept.
    factors.append(DiscreteFactor([graph.goal_zero_node_id], [2], [0.5, 0.5]))

    # Leaves are goals which never act as the parent of another goal.
    leaf_ids = set(goals_by_id) - set(child_ids_by_parent_id)
    # Only leaf confidences enter the model as observed-score likelihood factors.
    factors.extend(leaf_confidence_factor_factory(goals_by_id[leaf_id]) for leaf_id in sorted(leaf_ids))

    # Initialize the pgmpy bipartite factor graph.
    model = FactorGraph()
    # Add every goal ID as a binary variable node.
    model.add_nodes_from(goals_by_id)
    # Add the factor objects as the opposite side of the bipartite graph.
    model.add_factors(*factors)
    # Connect each factor to every variable in its scope.
    model.add_edges_from((variable, factor) for factor in factors for variable in factor.variables)
    # Ask pgmpy to verify factor scopes, cardinalities, and graph wiring.
    model.check_model()
    # Return the model ready for sum-product inference.
    return model


def confidence_graph_to_simple_bp_factor_graph(graph: ConfidenceGraph) -> FactorGraph:
    """Build the v1 factor graph using continuous confidence weights."""
    return _confidence_graph_to_simple_bp_factor_graph(graph, make_leaf_confidence_factor_v1)


def confidence_graph_to_simple_bp_goal_leaf_v2_factor_graph(graph: ConfidenceGraph) -> FactorGraph:
    """Build the v2 factor graph using binned score-emission probabilities."""
    return _confidence_graph_to_simple_bp_factor_graph(graph, make_leaf_confidence_factor_v2)


def _infer_goal_confidences(graph: ConfidenceGraph, model: FactorGraph) -> dict[str, float]:
    """Infer every goal's true-state marginal in a constructed factor graph."""
    goal_ids = [node.id for node in graph.nodes if isinstance(node, GSNGoalNode)]
    marginals = BeliefPropagationWithMessagePassing(model).query(variables=goal_ids)
    return {goal_id: float(marginals[goal_id].values[1]) for goal_id in goal_ids}


def infer_simple_bp_goal_leaf_v1_confidences(graph: ConfidenceGraph) -> dict[str, float]:
    """Infer each goal's true-state marginal from leaf-goal confidence observations."""
    return _infer_goal_confidences(graph, confidence_graph_to_simple_bp_factor_graph(graph))


def infer_simple_bp_goal_leaf_v2_confidences(graph: ConfidenceGraph) -> dict[str, float]:
    """Infer goal marginals from the v2 binned leaf-score emission model."""
    return _infer_goal_confidences(graph, confidence_graph_to_simple_bp_goal_leaf_v2_factor_graph(graph))


def _replace_goal_confidences(
    graph: ConfidenceGraph,
    confidences_by_goal_id: dict[str, float],
    *,
    aggregation_type: str,
) -> ConfidenceGraph:
    """Return a graph whose goal confidences are the supplied marginals."""
    return graph.model_copy(
        update={
            "nodes": [
                node.model_copy(
                    update={
                        "confidence": confidences_by_goal_id[node.id],
                        "confidence_rationale": outdated_aggregated_rationale(
                            aggregation_type, node.confidence_rationale
                        ),
                    }
                )
                if isinstance(node, GSNGoalNode)
                else node
                for node in graph.nodes
            ]
        }
    )


def aggregate_goal_confidences_with_simple_bp_goal_leaf_v1(graph: ConfidenceGraph) -> ConfidenceGraph:
    """Replace all goal confidences with their v1 goal-leaf belief-propagation marginals."""
    return _replace_goal_confidences(
        graph,
        infer_simple_bp_goal_leaf_v1_confidences(graph),
        aggregation_type="simple_bp_goal_leaf_v1",
    )


def aggregate_goal_confidences_with_simple_bp_goal_leaf_v2(graph: ConfidenceGraph) -> ConfidenceGraph:
    """Replace all goal confidences with their v2 goal-leaf belief-propagation marginals."""
    return _replace_goal_confidences(
        graph,
        infer_simple_bp_goal_leaf_v2_confidences(graph),
        aggregation_type="simple_bp_goal_leaf_v2",
    )
